#!/usr/bin/env python3
#
import argparse
import os, sys, time
from enum import Enum
from subprocess import Popen, PIPE


def parse_args():
    parser = argparse.ArgumentParser(
        prog="raid-sleep",
        description=
            "Power down and restart RAID disks simultaneously\n"
            "Copyright (c)2015-2022 Thomas Kindler <t_raid-sleep@kindler.xyz>\n"
            "\n"
            "%(prog)s comes with ABSOLUTELY NO WARRANTY. This is free software,\n"
            "and you are welcome to redistribute it under certain conditions.\n"
            "See the GNU General Public Licence version 3 (or later) for details.\n",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument(
        "--version", action="version",
        version="%(prog)s 2.0.0"
    )

    parser.add_argument(
        "-t", "--timeout", dest="timeout",
        default=1800, type=int,
        help="power down timeout in seconds (default: %(default)s)"
    )

    parser.add_argument(
        "monitor",
        help="RAID array to monitor for activity"
    )

    parser.add_argument(
        "disks", metavar="disk", nargs="+",
        help="disks to power up and down"
    )

    args = parser.parse_args()

    # convert /dev/disk/by-id/xxx to /dev/sda
    #
    args.monitor = os.path.realpath(args.monitor)
    args.disks = [os.path.realpath(d) for d in args.disks]

    return args


def hdparm_par(disks, *args):
    # execute hdparm in parallel for each disk
    #
    for p in [
        Popen(["hdparm", *args, "--", d], stdout=PIPE) for d in disks
    ]:
        if exitcode := p.wait():
            sys.exit(f"hdparm failed with exit code {exitcode}")


def power_down(disks):
    hdparm_par(disks, "-y")


def wake_up(disks):
    hdparm_par(disks, "--read-sector", "0")


def diskstats_line(devname):
    for line in open("/proc/diskstats"):
       if devname.removeprefix("/dev/") in line:
          return line
    else:
        sys.exit(f"{devname} not found")


def hms(s):
    return "%d:%02d:%02d" % (s / 3600, s / 60 % 60, s % 60)


if __name__ == "__main__":
    # Flush after newline
    #
    sys.stdout.reconfigure(line_buffering=True)
    sys.stderr.reconfigure(line_buffering=True)

    args = parse_args()

    print(f"Monitoring {args.monitor}, controlling {', '.join(args.disks)}, timeout={hms(args.timeout)}")

    State = Enum("State", ["UNKNOWN", "UP", "DOWN"])

    disk_state = State.UNKNOWN
    last_access = time.time()
    last_standby = last_access
    stats_old = None

    while True:
        now = time.time()
        stats = diskstats_line(args.monitor)

        if stats_old and stats_old != stats:
            if disk_state in [State.UNKNOWN, State.DOWN]:
                disk_state = State.UP
                last_standby = now
                print(f"Waking up after {hms(now - last_access)} of inactivity")
                wake_up(args.disks)

            last_access = now

        if now - last_access > args.timeout:
            if disk_state in [State.UNKNOWN, State.UP]:
                disk_state = State.DOWN
                print(f"Powering down after {hms(now - last_standby)}")
                power_down(args.disks)

        stats_old = stats

        time.sleep(60)
